application:
  number-of-studios: 3

logbook:
  format:
    style: http
  minimum-status: 400
  strategy: body-only-if-status-at-least

logging:
  level:
    root: warn
    service: info
    org.zalando.logbook: trace

server:
  shutdown: graceful

spring:
  application:
    name: oh3-studio-manager
  jackson:
    default-property-inclusion: non_null

---
spring.config.activate.on-profile: json-logging

logbook:
  format:
    style: json

logging:
  config: classpath:logback-json.xml
